markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
  # Dual-track approach: 1A = Ultra-minimal validation, 1B = Enterprise
  currentTrack: 1A  # Currently executing validation track
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
  - docs/architecture/index.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
qa:
  engine: octomind  # AI-powered testing
  octomind_test_target: "586f6fff-d148-4dda-a1b9-c3f6dd8d5968"
  fallback_to_playwright: true
  environments:
    production: "https://bmad-explore.vercel.app"
    local: "http://localhost:3000"
